
package com.ttech.calc.logic;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TTechWebServiceImplService", targetNamespace = "http://webservice.ttech.com/", wsdlLocation = "http://labs.turkcellteknoloji.com.tr/TTechWebService/ws/WebService?wsdl")
public class TTechWebServiceImplService
    extends Service
{

    private final static URL TTECHWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.ttech.calc.logic.TTechWebServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.ttech.calc.logic.TTechWebServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://labs.turkcellteknoloji.com.tr/TTechWebService/ws/WebService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://labs.turkcellteknoloji.com.tr/TTechWebService/ws/WebService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TTECHWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public TTechWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TTechWebServiceImplService() {
        super(TTECHWEBSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://webservice.ttech.com/", "TTechWebServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns TTechWebService
     */
    @WebEndpoint(name = "TTechWebServiceImplPort")
    public TTechWebService getTTechWebServiceImplPort() {
        return super.getPort(new QName("http://webservice.ttech.com/", "TTechWebServiceImplPort"), TTechWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TTechWebService
     */
    @WebEndpoint(name = "TTechWebServiceImplPort")
    public TTechWebService getTTechWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.ttech.com/", "TTechWebServiceImplPort"), TTechWebService.class, features);
    }

}
